-- MySQL Script generated by MySQL Workbench
-- Mon Feb 20 22:50:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8 ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(150) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  PRIMARY KEY (`idcliente`),
  UNIQUE INDEX `idcliente_UNIQUE` (`idcliente` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`bebida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`bebida` (
  `idbebida` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(115) NOT NULL,
  `imagen` BLOB NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idbebida`),
  UNIQUE INDEX `idhamburguesa_UNIQUE` (`idbebida` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`hamburguesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`hamburguesa` (
  `idhamburguesa` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(115) NOT NULL,
  `imagen` BLOB NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`idhamburguesa`),
  UNIQUE INDEX `idhamburguesa_UNIQUE` (`idhamburguesa` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`categoria_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`categoria_pizza` (
  `idcategoria_pizza` INT NOT NULL AUTO_INCREMENT,
  `nombre` ENUM('pizza', 'hambuerguesa', 'bebida') NOT NULL,
  PRIMARY KEY (`idcategoria_pizza`),
  UNIQUE INDEX `idcategoria_pizza_UNIQUE` (`idcategoria_pizza` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`pizza` (
  `idpizza` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(25) NOT NULL,
  `descripcion` VARCHAR(115) NOT NULL,
  `imagen` BLOB NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `idcategoria` INT NOT NULL,
  PRIMARY KEY (`idpizza`),
  UNIQUE INDEX `idpizza_UNIQUE` (`idpizza` ASC) ,
  INDEX `categoria_idx` (`idcategoria` ASC) ,
  CONSTRAINT `categoria`
    FOREIGN KEY (`idcategoria`)
    REFERENCES `Pizzeria`.`categoria_pizza` (`idcategoria_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`productos` (
  `idproductos` INT NOT NULL AUTO_INCREMENT,
  `producto` INT NOT NULL,
  PRIMARY KEY (`idproductos`),
  UNIQUE INDEX `idproductos_UNIQUE` (`idproductos` ASC),
  INDEX `producto_idx` (`producto` ASC),
  CONSTRAINT `fk_producto_bebida`
    FOREIGN KEY (`producto`)
    REFERENCES `Pizzeria`.`bebida` (`idbebida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_hamburguesa`
    FOREIGN KEY (`producto`)
    REFERENCES `Pizzeria`.`hamburguesa` (`idhamburguesa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_producto_pizza`
    FOREIGN KEY (`producto`)
    REFERENCES `Pizzeria`.`pizza` (`idpizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
)
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `Pizzeria`.`tienda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`tienda` (
  `idtienda` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` INT NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtienda`),
  UNIQUE INDEX `idtienda_UNIQUE` (`idtienda` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`empleado` (
  `idempleado` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(9) NOT NULL,
  `tefelono` INT NOT NULL,
  `categoria` ENUM('cocinero', 'repartidor') NOT NULL,
  `tienda` INT NOT NULL,
  PRIMARY KEY (`idempleado`),
  UNIQUE INDEX `idempleado_UNIQUE` (`idempleado` ASC) ,
  INDEX `tienda_idx` (`tienda` ASC) ,
  CONSTRAINT `tienda`
    FOREIGN KEY (`tienda`)
    REFERENCES `Pizzeria`.`tienda` (`idtienda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`comanda` (
  idcomanda INT NOT NULL AUTO_INCREMENT,
fecha_hora DATETIME NOT NULL,
cliente INT NOT NULL,
tipo_recogida VARCHAR(45) NOT NULL,
cantidad_productos INT NOT NULL,
precio_total DECIMAL(10,2) NOT NULL,
repartidor INT NULL,
hora_entrega DATETIME NULL,
tienda INT NOT NULL,
PRIMARY KEY (idcomanda),
UNIQUE INDEX idcomanda_UNIQUE (idcomanda ASC),
INDEX cliente_idx (cliente ASC),
INDEX repartidor_idx (repartidor ASC),
INDEX tienda_idx (tienda ASC),
CONSTRAINT comanda_cliente
FOREIGN KEY (cliente)
REFERENCES Pizzeria.cliente (idcliente)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT comanda_repartidor
FOREIGN KEY (repartidor)
REFERENCES Pizzeria.empleado (idempleado)
ON DELETE NO ACTION
ON UPDATE NO ACTION,
CONSTRAINT comanda_tienda
FOREIGN KEY (tienda)
REFERENCES Pizzeria.tienda (idtienda)
ON DELETE NO ACTION
ON UPDATE NO ACTION
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`comanda_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`comanda_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `comanda_idcomanda` INT NOT NULL,
  `productos_idproductos` INT NOT NULL,
  INDEX `fk_comanda_has_productos_productos1_idx` (`productos_idproductos` ASC) ,
  INDEX `fk_comanda_has_productos_comanda1_idx` (`comanda_idcomanda` ASC) ,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_comanda_has_productos_comanda1`
    FOREIGN KEY (`comanda_idcomanda`)
    REFERENCES `Pizzeria`.`comanda` (`idcomanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_comanda_has_productos_productos1`
    FOREIGN KEY (`productos_idproductos`)
    REFERENCES `Pizzeria`.`productos` (`idproductos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- ingreso dos tiendas en la tabla de tienda
USE Pizzeria;
INSERT INTO tienda (direccion, codigo_postal, localidad, provincia) 
VALUES ("Arago 33", 08001, "Barcelona","Barcelona"), ("Girona 45", 08003, "Sitges","Barcelona");
SELECT * FROM tienda;

-- ingreso dos empleados en cada tienda
 USE Pizzeria;
INSERT INTO empleado (nombre, apellido, NIF, tefelono, categoria, tienda) 
VALUES 
("Pablo", "Perez", "12345678A", 666666666, "cocinero", 1), 
("Martin", "Martinez", "12345678B", 677777777, "repartidor", 1),
("Juan", "Juarez", "12345678C", 688888888, "cocinero", 2), 
("Luciano", "Lopez", "12345678D", 699999999, "repartidor", 2);
SELECT * FROM empleado;

-- ingreso bebibas
USE Pizzeria;
INSERT INTO bebida (nombre, descripcion, precio) 
VALUES 
("Cerveza", "lata de cerveza de 300 ml", 2.5), 
("Refresco", "lata de refresco a elegir", 2.00),
("Agua", "botella de 500ml", 1.30), 
("Vino", "Vino de la casa", 7.45);
SELECT * FROM bebida;

USE Pizzeria;
INSERT INTO hamburguesa (nombre, descripcion, precio) 
VALUES 
("Vacuno", "Carne vacuna, lechuga, tomate", 15.5), 
("Pollo", "Carne de pollo, lechuga, tomate", 11.00),
("Vegana", "Hambueguesa vegetal, lechuga, tomate", 9.30); 
SELECT * FROM hamburguesa;

-- ingrreso pizzas
USE Pizzeria;
INSERT INTO categoria_pizza (nombre) 
VALUES 
("clasica"), 
("gourmet");
SELECT * FROM categoria_pizza;

INSERT INTO pizza (nombre, descripcion, precio, idcategoria) 
VALUES 
("Margarita", "Mozzarella, tomate", 9.50, 1), 
("Rucula", "Mozzarella, rucula, parmesano, tomate", 11.00,2),
("Burrata", "Mozzarella, burrata, tomate seco", 14.30, 2); 
SELECT * FROM pizza;

SELECT * FROM productos;
-- Insertar todas las bebidas
USE Pizzeria;
INSERT INTO productos (producto) SELECT idbebida FROM bebida;

-- Insertar todas las hamburguesas
INSERT INTO productos (producto) SELECT idhamburguesa FROM hamburguesa;

-- Insertar todas las pizzas
INSERT INTO productos (producto) SELECT idpizza FROM pizza;


-- ingreso 4 clientes
USE Pizzeria;
INSERT INTO cliente (nombre, apellido, direccion, codigo_postal, ciudad, provincia, telefono) 
VALUES 
("Ana", "Aguero", "Llanca 3", 08001, "Barcelona","Barcelona", 664321111), 
("Nuria", "Navarra", "Roma 6", 08003, "Barcelona","Barcelona", 664321112),
("Pilar", "Puig", "Paseo Maritimo 45", 08123, "Sitges","Barcelona", 664321113), 
("Luis", "Loque", "Vic 67", 08123, "Sitges","Barcelona", 664321114);
SELECT * FROM cliente;

-- ingreso comandas
USE Pizzeria;
INSERT INTO comanda (fecha_hora, cliente, tipo_recogida, cantidad_productos, precio_total, repartidor, hora_entrega, tienda) 
VALUES 
("2023-02-23 21:22:00", 1, "a domicilio", 2, 16.00, 6, "2023-02-23 22:22:00", 1);
SELECT * FROM comanda;
INSERT INTO comanda_detail (comanda_idcomanda, productos_idproductos) 
VALUES 
( 1, 3 );
SELECT * FROM comanda_detail;

-- para consultar las bebidas vendidas en una ciudad en particular
SELECT COUNT(DISTINCT comanda.idcomanda) AS cantidad_bebidas
FROM comanda
INNER JOIN productos_comanda ON comanda.idcomanda = comanda_detail.idcomanda
INNER JOIN productos ON comanda_detail.idproducto = productos.idproducto
INNER JOIN bebida ON productos.producto = bebida.idbebida
INNER JOIN cliente ON comanda.idcliente = cliente.idcliente
WHERE cliente.localidad = "Barcelona";

-- para consultar comandas que hizo un determinado empleado
SELECT COUNT(*) AS comanda
FROM comanda
WHERE repartidor = 2;

